//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaModelo
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Password
    {
        public int id { get; set; }
        public string descripcion { get; set; }
        [StringLength(200)]
        public string pass { get; set; }
        public Nullable<int> userID { get; set; }
        public Nullable<int> position { get; set; }
    }
}
